services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: web_app
    restart: unless-stopped
    container_name: web
    env_file:
      - .env.mysql
      - .env.mongo
      - .env.web
    environment:
      - MONGO_HOSTNAME=mongo
      - MYSQL_HOSTNAME=mysql
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    # for hot changes/dev testing
    # volumes:
    #   - ./web:/home/node/app
    networks:
      - app
    depends_on:
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # analytics:
  #   volumes:
  #     - analytics:
  #   networks:
  #     - app

  mongo:
    image: mongo:8.0.4
    restart: unless-stopped
    container_name: mongo
    env_file:
      - .env.mongo
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:$$MONGO_PORT/test --quiet
      start_period: 5s
      interval: 60s
      timeout: 5s
      retries: 10

  mongo-express:
    image: mongo-express:1.0.2
    restart: unless-stopped
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env.mongo
      - .env.mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - app
    depends_on:
      mongo:
        condition: service_healthy

  mysql:
    image: mysql:9.2.0
    restart: unless-stopped
    container_name: mysql
    env_file: 
      - .env.mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app
    healthcheck:
      test: mysqladmin ping -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app:
    driver: bridge

volumes:
  web:
  analytics:
  mongo:
  mysql: