apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: jparras1/analytics:latest
          envFrom:
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: mongo-secret
          env:
          - name: MONGO_HOSTNAME
            value: mongo
          - name: MYSQL_HOSTNAME
            value: mysql
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do sleep 2; done;']
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo 27017; do sleep 2; done;']