apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: jparras1/analytics:latest
          envFrom:
          - configMapRef:
              name: mysql-config
          - configMapRef:
              name: mongo-config
          env:
          - name: MONGO_HOSTNAME
            value: mongo
          - name: MYSQL_HOSTNAME
            value: mysql
          # readinessProbe:
          #   httpGet:
          #     path: /health # add to app.js just to see the health of the pod?
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do sleep 2; done;']
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo 27017; do sleep 2; done;']