apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:8.0.4
        envFrom:
          - configMapRef:
              name: mongo-config
        volumeMounts:
          - mountPath: "/data/db"
            name: mongo-storage
        ports:
          - containerPort: 27017
        readinessProbe:
          exec:
            command: ["mongosh", "--eval", "db.runCommand({ ping: 1 })"]
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc