apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:9.2.0
        envFrom:
          - configMapRef:
              name: mysql-config
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-storage
        ports:
          - containerPort: 3306
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc