apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: migration
        image: jparras1/migration:latest
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
        command: ["sh", "-c", "until nc -z mysql 3306; do sleep 2; done; echo 'MySQL is ready! Starting migration...'; npx knex migrate:latest; echo 'Migration completed!'"]
      containers:
      - name: web
        image: jparras1/migration:latest
        envFrom:
          - configMapRef:
              name: web-config
          - secretRef:
              name: web-secret
          - configMapRef:
              name: mysql-config
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: mongo-config
          - secretRef:
              name: mongo-secret
        ports:
          - containerPort: 3000
        # readinessProbe:
        #   httpGet:
        #     path: "/health"
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: web